// "use client";
import store from "@/store";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientProvider from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mica Transportation",
  description: "Generated by TechEthio IT Solutions PLC",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <Provider store={store}>{children}</Provider> */}
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
